services:
    advert.handler.form:
        class: Piface\AppBundle\Form\Handler\AdvertHandler
        scope: request
        arguments:
         - '@request'
         - '@doctrine.orm.entity_manager'
         - '@event_dispatcher'

    filter.advert.handler.form:
        class: Piface\AppBundle\Form\Handler\FiltreAdvertHandler
        scope: request
        arguments:
          - '@request'
          - '@app.advert.manager'

