parameters:
    #-- base
    app.base.manager.class: Piface\AppBundle\Manager\Base\BaseManager

services:
    # -- base manager
        app.base.manager:
            abstract: true
            class: %app.base.manager.class%
            arguments:
                - "@doctrine.orm.entity_manager"

        app.advert.manager:
            class: Piface\AppBundle\Manager\AdvertManager
            parent: app.base.manager
            tags:
                - { name: app.manager }