piface_app_home:
    path:      /
    defaults:  { _controller: PifaceAppBundle:Home:index }

piface_app_advert_list:
    path:      /adverts/offers
    defaults: { _controller: PifaceAppBundle:Advert:list }

piface_app_advert:
    path:      /advert/offer/{id}
    defaults: { _controller: PifaceAppBundle:Advert:show }


#Espace personnel user
piface_app_my_advert_list:
    path:     /account/adverts-save
    defaults: { _controller: PifaceAppBundle:UserAdvert:list }

piface_app_advert_add:
    path:      /advert/add
    defaults: { _controller: PifaceAppBundle:UserAdvert:add }

piface_app_my_advert_delete:
    path:    /account/delete/{id}
    defaults: { _controller: PifaceAppBundle:UserAdvert:delete }

piface_app_my_advert_edit:
    path:    /account/advert/edit/{id}
    defaults: { _controller: PifaceAppBundle:UserAdvert:edit }

piface_app_dashboard:
    path:    /account/dash-board
    defaults: { _controller: PifaceAppBundle:Dashboard:show }
