parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: Piface\UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: piface_user_registration }
