<?php

/**
 * Created by PhpStorm.
 * User: maxime.joassy
 * Date: 07/03/2017
 * Time: 11:07
 */

namespace Piface\AppBundle\Manager;

use Piface\AppBundle\Manager\Base\BaseManager;
use Piface\AppBundle\Repository\AdvertRepository;

class AdvertManager extends BaseManager
{
    public function getEntityName()
    {
        return 'PifaceAppBundle:Advert';
    }

    /**
     * @return AdvertRepository
     */
    public function getRepository()
    {
        return parent::getRepository(); // TODO: Change the autogenerated stub
    }

    public function countAdvert($id)
    {
        return $this->getRepository()->countAdvert($id);
    }

    public function getAdverts()
    {
        return $this->getRepository()->getAdverts();
    }

    public function findByCategory($category)
    {
        return $this->getRepository()->findByCategory($category);
    }

    public function getMyAdverts($id)
    {
        return $this->getRepository()->getMyAdverts($id);
    }

    public function findByKeyWord($keyWord)
    {
        return $this->getRepository()->findByKeyWord($keyWord);
    }

    public function findByOptions($category, $keyWord)
    {
        return $this->getRepository()->findByOptions($category, $keyWord);
    }

    public function isAuthorized($id)
    {
        return $this->getRepository()->isAuthorized($id);
    }

    public function getOffCharter($advertId)
    {
        return $this->getRepository()->getOffCharter($advertId);
    }
}
