<?php
/**
 * Created by PhpStorm.
 * User: maxime.joassy
 * Date: 03/04/2017
 * Time: 09:47
 */

namespace Piface\AppBundle\Manager;


use Piface\AppBundle\Manager\Base\BaseManager;
use Piface\AppBundle\Repository\AdvertRepository;

class CategoryManager extends BaseManager
{
    public function getEntityName()
    {
        return 'PifaceAppBundle:Category';
    }

    /**
     * @return AdvertRepository
     */
    public function getRepository()
    {
        return parent::getRepository(); // TODO: Change the autogenerated stub
    }
}
